namespace rxApp.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class v12 : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.message_get_status",
                c => new
                    {
                        Id = c.Long(nullable: false, identity: true),
                        TopicDeviceId = c.Int(nullable: false),
                        Destiny = c.Int(nullable: false),
                        DeviceSensors = c.Long(nullable: false),
                        DeviceSensorsBit0 = c.Int(nullable: false),
                        DeviceSensorsBit1 = c.Int(nullable: false),
                        DeviceSensorsBit2 = c.Int(nullable: false),
                        DeviceSensorsBit3 = c.Int(nullable: false),
                        DeviceSensorsBit4 = c.Int(nullable: false),
                        DeviceSensorsBit5 = c.Int(nullable: false),
                        DeviceSensorsBit6 = c.Int(nullable: false),
                        DeviceSensorsBit7 = c.Int(nullable: false),
                        DeviceSensorsBit8 = c.Int(nullable: false),
                        DeviceSensorsBit9 = c.Int(nullable: false),
                        DeviceSensorsBit10 = c.Int(nullable: false),
                        DeviceSensorsBit11 = c.Int(nullable: false),
                        DeviceSensorsBit12 = c.Int(nullable: false),
                        DeviceSensorsBit13 = c.Int(nullable: false),
                        DeviceSensorsBit14 = c.Int(nullable: false),
                        DeviceSensorsBit15 = c.Int(nullable: false),
                        DeviceSensorsBit16 = c.Int(nullable: false),
                        DeviceSensorsBit17 = c.Int(nullable: false),
                        DeviceSensorsBit18 = c.Int(nullable: false),
                        DeviceSensorsBit19 = c.Int(nullable: false),
                        DeviceSensorsBit20 = c.Int(nullable: false),
                        DeviceSensorsBit21 = c.Int(nullable: false),
                        DeviceSensorsBit22 = c.Int(nullable: false),
                        DeviceSensorsBit23 = c.Int(nullable: false),
                        DeviceSensorsBit24 = c.Int(nullable: false),
                        DeviceSensorsBit25 = c.Int(nullable: false),
                        DeviceSensorsBit26 = c.Int(nullable: false),
                        DeviceSensorsBit27 = c.Int(nullable: false),
                        DeviceSensorsBit28 = c.Int(nullable: false),
                        DeviceSensorsBit29 = c.Int(nullable: false),
                        DeviceSensorsBit30 = c.Int(nullable: false),
                        DeviceSensorsBit31 = c.Int(nullable: false),
                        BillMachineStatus = c.Long(nullable: false),
                        BillMachineStatusBit0 = c.Int(nullable: false),
                        BillMachineStatusBit1 = c.Int(nullable: false),
                        BillMachineStatusBit2 = c.Int(nullable: false),
                        BillMachineStatusBit3 = c.Int(nullable: false),
                        BillMachineStatusBit4 = c.Int(nullable: false),
                        BillMachineStatusBit5 = c.Int(nullable: false),
                        BillMachineStatusBit6 = c.Int(nullable: false),
                        BillMachineStatusBit7 = c.Int(nullable: false),
                        BillMachineStatusBit8 = c.Int(nullable: false),
                        BillMachineStatusBit9 = c.Int(nullable: false),
                        BillMachineStatusBit10 = c.Int(nullable: false),
                        BillMachineStatusBit11 = c.Int(nullable: false),
                        BillMachineStatusBit12 = c.Int(nullable: false),
                        BillMachineStatusBit13 = c.Int(nullable: false),
                        BillMachineStatusBit14 = c.Int(nullable: false),
                        BillMachineStatusBit15 = c.Int(nullable: false),
                        BillMachineStatusBit16 = c.Int(nullable: false),
                        BillMachineStatusBit17 = c.Int(nullable: false),
                        BillMachineStatusBit18 = c.Int(nullable: false),
                        BillMachineStatusBit19 = c.Int(nullable: false),
                        BillMachineStatusBit20 = c.Int(nullable: false),
                        BillMachineStatusBit21 = c.Int(nullable: false),
                        BillMachineStatusBit22 = c.Int(nullable: false),
                        BillMachineStatusBit23 = c.Int(nullable: false),
                        BillMachineStatusBit24 = c.Int(nullable: false),
                        BillMachineStatusBit25 = c.Int(nullable: false),
                        BillMachineStatusBit26 = c.Int(nullable: false),
                        BillMachineStatusBit27 = c.Int(nullable: false),
                        BillMachineStatusBit28 = c.Int(nullable: false),
                        BillMachineStatusBit29 = c.Int(nullable: false),
                        BillMachineStatusBit30 = c.Int(nullable: false),
                        BillMachineStatusBit31 = c.Int(nullable: false),
                        BillMachineError = c.Long(nullable: false),
                        BillMachineErrorBit0 = c.Int(nullable: false),
                        BillMachineErrorBit1 = c.Int(nullable: false),
                        BillMachineErrorBit2 = c.Int(nullable: false),
                        BillMachineErrorBit3 = c.Int(nullable: false),
                        BillMachineErrorBit4 = c.Int(nullable: false),
                        BillMachineErrorBit5 = c.Int(nullable: false),
                        BillMachineErrorBit6 = c.Int(nullable: false),
                        BillMachineErrorBit7 = c.Int(nullable: false),
                        BillMachineErrorBit8 = c.Int(nullable: false),
                        BillMachineErrorBit9 = c.Int(nullable: false),
                        BillMachineErrorBit10 = c.Int(nullable: false),
                        BillMachineErrorBit11 = c.Int(nullable: false),
                        BillMachineErrorBit12 = c.Int(nullable: false),
                        BillMachineErrorBit13 = c.Int(nullable: false),
                        BillMachineErrorBit14 = c.Int(nullable: false),
                        BillMachineErrorBit15 = c.Int(nullable: false),
                        BillMachineErrorBit16 = c.Int(nullable: false),
                        BillMachineErrorBit17 = c.Int(nullable: false),
                        BillMachineErrorBit18 = c.Int(nullable: false),
                        BillMachineErrorBit19 = c.Int(nullable: false),
                        BillMachineErrorBit20 = c.Int(nullable: false),
                        BillMachineErrorBit21 = c.Int(nullable: false),
                        BillMachineErrorBit22 = c.Int(nullable: false),
                        BillMachineErrorBit23 = c.Int(nullable: false),
                        BillMachineErrorBit24 = c.Int(nullable: false),
                        BillMachineErrorBit25 = c.Int(nullable: false),
                        BillMachineErrorBit26 = c.Int(nullable: false),
                        BillMachineErrorBit27 = c.Int(nullable: false),
                        BillMachineErrorBit28 = c.Int(nullable: false),
                        BillMachineErrorBit29 = c.Int(nullable: false),
                        BillMachineErrorBit30 = c.Int(nullable: false),
                        BillMachineErrorBit31 = c.Int(nullable: false),
                        LevelSensor = c.Long(nullable: false),
                        UptimeSec = c.Long(nullable: false),
                        trackLastWriteTime = c.DateTime(),
                        trackCreationTime = c.DateTime(),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.message_get_status");
        }
    }
}
