// <auto-generated />
namespace rxApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v037 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v037));
        
        string IMigrationMetadata.Id
        {
            get { return "202504191316394_v037"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
